import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Suspense } from 'react';
import Team from './@teams/page';
import Analitics from './@analitics/page';
import Teams from './@teams/page';
import Link from 'next/link';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				style={{ padding: 20 }}
				className={`${geistSans.variable} ${geistMono.variable}`}
			>
				<h1>Main Layout</h1>

				<nav style={{ padding: 10 }}>
					<Link style={{ color: 'blue' }} href={'/admin'}>
						Admin Link
					</Link>
				</nav>
				<hr />

				{children}

				<hr></hr>

				<Suspense fallback={<div>Analitics loading...</div>}>
					<Analitics />
				</Suspense>

				<Suspense fallback={<div>Teams loading...</div>}>
					<Teams />
				</Suspense>
			</body>
		</html>
	);
}
