import Image from 'next/image';
import styles from './page.module.css';
import { Metadata } from 'next';
import LoginForm from './components/login.form.component';
import SendEmail from './components/send.email.component';

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
};

export default function Home() {
	return (
		<div>
			<p>Home Page</p>

			<LoginForm />
			<br></br>
			<hr></hr>
			<SendEmail />
		</div>
	);
}
